# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2632e37d6d0e635167ca5b84b5a9331122c8ffc18f8b7a966b31f04633cd526cd1e3e32b7110a41fa1242b9abe41cd2bba74ceb1ae62333d7f065de66eccab92

test:
  secret_key_base: 6bf88b6266e2ce125429f4fee4d5a9c7e72c35e7df3e1c1ac7fcbb3fe5886ce6da18331641b8756fb0f2ac10b69f2ed8e556104fa605ccc5e0f5754c07a6869a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
